apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    permissions:
    - configure: .*
      read: .*
      write: .*
    user: mctest
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: mctest
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - administrator

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/permissions
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
