apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Policy
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
    policy:
    - applyTo: all
      definition:
        ha-mode: all
      pattern: .*
      priority: 0
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: guest

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: guest
  name: guest
spec:
  forProvider:
    permissions:
    - configure: .*
      read: .*
      write: .*
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/policy
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
