apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Queue
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
    settings:
    - arguments:
        x-queue-type: quorum
      autoDelete: true
      durable: false
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: guest

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Permissions
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: guest
  name: guest
spec:
  forProvider:
    permissions:
    - configure: .*
      read: .*
      write: .*
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    vhostSelector:
      matchLabels:
        testing.upbound.io/example-name: test

---

apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: Vhost
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/queue
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: test
