apiVersion: rabbitmq.evaneos.com/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: rabbitmq/v1alpha1/user
  labels:
    testing.upbound.io/example-name: test
  name: test
spec:
  forProvider:
    name: mctest
    passwordSecretRef:
      key: example-key
      name: example-secret
      namespace: upbound-system
    tags:
    - administrator
    - management
