// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type VhostInitParameters struct {

	// The name of the vhost.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type VhostObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the vhost.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type VhostParameters struct {

	// The name of the vhost.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// VhostSpec defines the desired state of Vhost
type VhostSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VhostParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VhostInitParameters `json:"initProvider,omitempty"`
}

// VhostStatus defines the observed state of Vhost.
type VhostStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        VhostObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Vhost is the Schema for the Vhosts API. Creates and manages a vhost on a RabbitMQ server.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,rabbitmq}
type Vhost struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   VhostSpec   `json:"spec"`
	Status VhostStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VhostList contains a list of Vhosts
type VhostList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Vhost `json:"items"`
}

// Repository type metadata.
var (
	Vhost_Kind             = "Vhost"
	Vhost_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Vhost_Kind}.String()
	Vhost_KindAPIVersion   = Vhost_Kind + "." + CRDGroupVersion.String()
	Vhost_GroupVersionKind = CRDGroupVersion.WithKind(Vhost_Kind)
)

func init() {
	SchemeBuilder.Register(&Vhost{}, &VhostList{})
}
